### ISSUE TITLE
Global nav drops to bottom of viewport on smaller breakpoints

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/global-nav#108]
View the site using Chrome DevTools to emulate smaller screen sizes:

<img width="413" alt="Screenshot 2019-05-08 at 14 10 13" src="https://user-images.githubusercontent.com/505570/57377809-40a5fb80-719b-11e9-8854-0d859c3c049e.png">

**Comment by anthonydillon** [comment]
@anasereijo @spencerbygraves I think this is an interesting suggestion. We originality pushed the global-nav to the footer on small screens as there were a lot of links and it scaled better there.

Now that there are fewer it should fit at the top. Also, with the drive to raise the awareness of Canonical it would be better to keep the Canonical logo at the top.

If we add global login and authentication to the global-nav it would make more sense to sit at the top even on small screens.

**Comment by spencerbygraves** [comment]
@anthonydillon yes, I think it makes sense for it to be at the top of the page. Perhaps this needs UX sign off though. cc @clagom for his opinion.

**Comment by barrymcgee** [comment]
It's very weird for it to be at the bottom imo - I immediately thought it was a positioning bug.

**Comment by clagom** [comment]
I agree, top of the page makes sense. As Ant pointed out, especially for the login options and for Canonical branding.

**Comment by clagom** [comment]
Also, I think we can keep the horizontal alignment:
[ Canonical                            products      login  ]
