### ISSUE TITLE
NodeList.forEach doesn't always exist.

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/global-nav#122]
We have been getting a number of errors on jaas.ai because [NodeList](https://developer.mozilla.org/en-US/docs/Web/API/NodeList) does not have a `forEach` method in older browsers. In the following line `headerLinks` therefore does not return an object which has a `forEach` function.

https://github.com/canonical-web-and-design/global-nav/blob/af963ffc4ac1e34c138d31715744421d3a220a56/src/js/global-nav.js#L261

Even though these browsers are outside of our supported matrix we should make it more resilient. The fix here is rather trivial by modifying the iterator we use to loop over the collection.

**Comment by anthonydillon** [comment]
Setting to high as this effects all sites using the global-nav
