### ISSUE TITLE
Injecting the global nav into top of page flow causes jarring jump

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/global-nav#129]
After the page is rendered and painted, the global nav injection script fires, pushes all page content down by 32px and causes the page render and paint process to refire meaning the whole process is intensive and feels slow.

See on Ubuntu: https://cl.ly/8eb99b16eb16

See on demo page: https://cl.ly/dfed49e5b80c

By adding a placeholder div into the page, 32px high with a black background, this jump disappears and the whole process becomes indecipherable: https://cl.ly/9d00c55b8aab

**Comment by sowasred2012** [comment]
Closing, this has been addressed: https://github.com/canonical-web-and-design/ubuntu.com/blob/main/static/sass/styles.scss#L812
