### ISSUE TITLE
Link to jobs in console is a 404

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/global-nav#152]
This link is a 404: https://github.com/canonical-web-and-design/global-nav/blob/master/src/js/global-nav.js#L293

It should link to: https://canonical.com/careers/engineering#available-roles

We should update the shortened .eu link to point to the above link.

**Comment by SirSamTumless** [comment]
Peter has temporarily fixed this with a redirect. We should look into a longer-term solution.

**Comment by pmahnke** [comment]
I think the redirect is a good solution.  Closing this.
