### ISSUE TITLE
Consider making background color different from default dark Vanilla top navigation

### ISSUE THREAD

**Issue by fitojb** [canonical-web-and-design/global-nav#213]
Both bars used to be distinguishable by color, as one was slightly darker than the other, but this has been lost with time. This muddies the clear visual hierarchy that the sites had.

**Comment by sowasred2012** [comment]
@fitojb it's a very good point, thanks for raising it. 

However, very soon we'll be making an update to the navigation on each site, which includes combining the items in this bar with the bar below, so this won't be a problem for much longer.
