### ISSUE TITLE
Allow injection of additional links

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/global-nav#46]
On snapcraft.io we want to add a "We're hiring" link, seems it would ideally be injected into the global nav. Other sites may also have use for this in the future.

![screenshot_2018-09-13 the leading operating system for pcs iot devices servers and the cloud ubuntu](https://user-images.githubusercontent.com/479384/45490367-c8e41600-b75e-11e8-8d84-c0ed5e8e8ea6.png)

**Comment by anthonydillon** [comment]
This was added here: https://github.com/canonical-web-and-design/global-nav/pull/134
