### ISSUE TITLE
MacOS - closed nav visible on scroll

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/global-nav#61]
MacOS has 'elastic scroll' allowing you to scroll over the top or bottom of the page.
This makes global-nav dropdown visible.

1. Go to page with global nav on MacOS (https://ubuntu.com, https://microk8s.io, https://mir-server.io)
2. Scroll up (over the edge of the page) - white backround will appear over the global nav
3. Open global nav Products
4. Close global nav Products
5. Scroll up again over the top edge

The bottom of "Products" menu is visible. If you scroll fast you can see quite a bunch of it:
<img width="1265" alt="screen shot 2018-12-14 at 11 55 38" src="https://user-images.githubusercontent.com/83575/50003440-e7e38580-ffa3-11e8-81bc-37634d1dd37b.png">

Discovered when QAing https://github.com/canonical-websites/snapcraft.io/pull/1449

**Comment by barrymcgee** [comment]
@bartaz I can't replicate this, is it still valid?

**Comment by bartaz** [comment]
I can reproduce it on ubuntu.com, snapcraft.io:

<img width="1920" alt="screenshot 2019-02-22 at 22 31 05" src="https://user-images.githubusercontent.com/83575/53272470-b3055480-36f1-11e9-8ded-f8b2d2557dae.png">

Make sure you open 'Product' dropdown in global nav first, close it, and then scroll.
It works fine (nothing shows up) after fresh load.

**Comment by lyubomir-popov** [comment]
To replicate, show/hide Products or Login. Seems to be related to the fade. Deleting the fade fixes it.

**Comment by lyubomir-popov** [comment]
(Not suggesting deleting the fade is a valid fix, just that it's probably the culprit)

**Comment by tbille** [comment]
@bartaz is this still relevant?

**Comment by bartaz** [comment]
![nav](https://user-images.githubusercontent.com/83575/59910711-c65fcc80-9412-11e9-8ac3-1763b70e48dd.gif)

**Comment by bartaz** [comment]
Seems to be fixed on Chrome 75.

**Comment by solazio** [comment]
Closing as this is fixed in Chrome 75 or newer.
