### ISSUE TITLE
Considering Careers on the global nav

### ISSUE THREAD

**Issue by therealjuan** [canonical-web-and-design/global-nav#63]
As part of the global navigation, it will be good to consider other sections that might be of interesting when you are visiting a product from Canonical. For example, careers.

Just thinking out loud here but at Europython we had many developers asking for who was behind snapcraft as it is a nebulous term looking through the site. When we mentioned Canonical being the company behind snaps, then the Canonical brand and the ubuntu one lifted our pitch with positive resonance related to these brands in the dev community.

In regards to Careers, a big percentage of our new positions available are for engineers. Taking into account that the main audience for snapcraft are developers, it will be easier to find prospective candidates within users of the platform rather than looking outside. Since Canonical is ultimately the company hiring, it will make sense to find some space in the global nav for careers.

Might be good to find some time to discuss as a WG initiative at some point.

**Comment by anthonydillon** [comment]
This was done https://github.com/canonical-web-and-design/global-nav/pull/134
